worker_processes auto; # auto detects the number of cpu cores and start one worker per core.

events {
    worker_connections 1024; # max simlutaneous connections per worker
}
http {
    include mime.types;

    upstream backend_servers {
        # server backend:8000;
        server localhost:8000;
    }

    # rate limiting zones
    limit_req_zone $binary_remote_addr zone=auth_zone:10m rate=30r/m;
    limit_req_zone $binary_remote_addr zone=ws_zone:10m rate=10r/m;


    server {
        listen 80;
        server_name collabdocs.example.com;

        # ── Frontend (static files) ──────────────────────────────────
        location / {
            root /frontend/dist;
            try_files $uri $uri/ /index.html;
        }

        # ── Backend API ──────────────────────────────────────────────
        location /auth/ {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # rate limiting
            limit_req zone=auth_zone burst=10 nodelay;
        }

        # ── WebSocket ────────────────────────────────────────────────
        location /ws/ {
            proxy_pass http://backend_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 86400s; # keep ws alive for 24h

            limit_req zone=ws_zone burst=5 nodelay;
        }
    }
}